const express = require('express');
const app = express();
const cookie = require('cookie-parser');
const cors = require('cors');
const products = require('./routes/product');
const auth = require('./routes/auth');
const orders = require('./routes/order');
app.use(express.json());
app.use(cors());
app.use(cookie());
app.use('/api/v1',products);
app.use('/api/v1', auth);
app.use('/api/v1',orders);
module.exports = app;